name: Setup Node
description: This action sets up Node.js environment
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        cache: pnpm
        cache-dependency-path: "pnpm-lock.yaml"
    - run: npm run setup
      shell: bash
    - run: pnpm i
      shell: bash
