volumes:
  db-data:

services:
  dev-db:
    image: postgres:17
    env_file: .env.local
    ports:
      - "5432:5432"
  test-db:
    image: postgres:17
    env_file: .env.test
    ports:
      - "5433:5432"
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      # frontend
      - "16686:16686"
      - "14268"
      - "14250"
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=true
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
    depends_on:
      - jaeger
  sendgrid-maildev:
    image: ykanazawa/sendgrid-maildev
    hostname: sendgrid-maildev
    environment:
      - SENDGRID_DEV_API_SERVER=:3030
      - SENDGRID_DEV_API_KEY=SG.xxxxx
      - SENDGRID_DEV_SMTP_SERVER=127.0.0.1:1025
    container_name: sendgrid-maildev
    ports:
      - 1025:1025
      - 1080:1080
      - 3030:3030
